name: Build & Deploy Android SDk
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF:10}

    - uses: actions/checkout@v1 # 将仓库内容拷贝到Ubuntu系统的虚拟环境
    - name: Build the Docker image # 步骤名字
      run: |
        docker build -t docker-android-sdk:latest . #执行构建

    - name: Login Aliyun
      run: |
        docker login --username=${{ secrets.DOCKER_USN }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_PWD }} # 登录docker，并使用Secret里配置的参数

    - name: Tag Images
      run: |
        docker tag docker-android-sdk registry.cn-hangzhou.aliyuncs.com/xiaoman-cn/docker-android-sdk:latest
        docker tag docker-android-sdk registry.cn-hangzhou.aliyuncs.com/xiaoman-cn/docker-android-sdk:${{ steps.vars.outputs.tag }}

    - name: Push To Aliyun
      run: |
        # 推送
        docker push registry.cn-hangzhou.aliyuncs.com/xiaoman-cn/docker-android-sdk:latest
        # 做远程标记
        docker push registry.cn-hangzhou.aliyuncs.com/xiaoman-cn/docker-android-sdk:${{ steps.vars.outputs.tag }}
